# frozen_string_literal: true

module Legion
  module Extensions
    module Detect
      module Formatters
        module MarkdownPr
          module_function

          def format(detections)
            missing   = collect_missing(detections)
            installed = collect_installed(detections)

            lines = ["## Legion Detect Findings\n"]

            if missing.any?
              lines << "### Missing Extensions (#{missing.size})\n"
              missing.each do |m|
                lines << "- **#{m[:name]}**: `#{m[:extension]}` not installed"
                lines << "  Detected by: #{m[:signals].join(', ')}"
                lines << "  Install: `gem install #{m[:extension]}`\n"
              end
            end

            if installed.any?
              lines << "### Installed (#{installed.size})\n"
              installed.each do |i|
                lines << "- #{i[:name]}: `#{i[:extension]}` :white_check_mark:"
              end
            end

            lines << "No extensions detected.\n" if missing.empty? && installed.empty?

            lines << "\n---\n*Generated by legion-detect v#{VERSION}*"
            lines.join("\n")
          end

          def collect_missing(detections)
            detections.flat_map do |d|
              d[:extensions].filter_map do |ext|
                next if d[:installed][ext]

                { name: d[:name], extension: ext, signals: d[:matched_signals] }
              end
            end
          end

          def collect_installed(detections)
            detections.flat_map do |d|
              d[:extensions].filter_map do |ext|
                next unless d[:installed][ext]

                { name: d[:name], extension: ext }
              end
            end
          end
        end
      end
    end
  end
end
